/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/protected/cardapio`; params?: Router.UnknownInputParams; } | { pathname: `/protected/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/protected/employeeOrders`; params?: Router.UnknownInputParams; } | { pathname: `/protected/employeeOrdersDetails`; params?: Router.UnknownInputParams; } | { pathname: `/protected/home`; params?: Router.UnknownInputParams; } | { pathname: `/protected/orders`; params?: Router.UnknownInputParams; } | { pathname: `/protected/payment`; params?: Router.UnknownInputParams; } | { pathname: `/protected/productDetails`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/protected/cardapio`; params?: Router.UnknownOutputParams; } | { pathname: `/protected/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/protected/employeeOrders`; params?: Router.UnknownOutputParams; } | { pathname: `/protected/employeeOrdersDetails`; params?: Router.UnknownOutputParams; } | { pathname: `/protected/home`; params?: Router.UnknownOutputParams; } | { pathname: `/protected/orders`; params?: Router.UnknownOutputParams; } | { pathname: `/protected/payment`; params?: Router.UnknownOutputParams; } | { pathname: `/protected/productDetails`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/cadastro${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/protected/cardapio${`?${string}` | `#${string}` | ''}` | `/protected/dashboard${`?${string}` | `#${string}` | ''}` | `/protected/employeeOrders${`?${string}` | `#${string}` | ''}` | `/protected/employeeOrdersDetails${`?${string}` | `#${string}` | ''}` | `/protected/home${`?${string}` | `#${string}` | ''}` | `/protected/orders${`?${string}` | `#${string}` | ''}` | `/protected/payment${`?${string}` | `#${string}` | ''}` | `/protected/productDetails${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/protected/cardapio`; params?: Router.UnknownInputParams; } | { pathname: `/protected/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/protected/employeeOrders`; params?: Router.UnknownInputParams; } | { pathname: `/protected/employeeOrdersDetails`; params?: Router.UnknownInputParams; } | { pathname: `/protected/home`; params?: Router.UnknownInputParams; } | { pathname: `/protected/orders`; params?: Router.UnknownInputParams; } | { pathname: `/protected/payment`; params?: Router.UnknownInputParams; } | { pathname: `/protected/productDetails`; params?: Router.UnknownInputParams; };
    }
  }
}
