services:
  # BANCO DE DADOS (MySQL)
  urbancandy-db:
    image: mysql:8.0
    container_name: urbancandy-mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: urbancandy_dockercompose
      MYSQL_ROOT_PASSWORD: ADMIN
    ports:
      - '3306:3306' 
    volumes:
      - urbancandy_db_data:/var/lib/mysql
    networks:
      - urbancandy-network
    command: --default-authentication-plugin=mysql_native_password

  #  BACKEND 
  urbancandy-backend:
    container_name: urbancandy-backend-container
    restart: on-failure
    build: ./UrbanCandy_back 
    image: urbancandy-backend:v7
    ports:
      - '3030:3000' 
    environment:
      JWT_SECRET: ${JWT_SECRET}    
      PORT: 3030                    
      DB_HOST: ${DB_HOST}           
      DB_USER: ${DB_USER}           
      DB_PASSWORD: ${DB_PASSWORD}   
      DB_NAME: ${DB_NAME}          
    volumes:
      - ./UrbanCandy_back:/app
      - /app/node_modules
      - /app/dist             
      - ./UrbanCandy_back/uploads:/app/uploads
    networks:
      - urbancandy-network
    depends_on:
      - urbancandy-db

  # FRONTEND
  urbancandy-frontend:
    image: urbancandy-frontend:latest
    container_name: urbancandy-frontend-container
    restart: always
    ports:
      - '5173:5173' 
    networks:
      - urbancandy-network

volumes:
  urbancandy_db_data:

networks:
  urbancandy-network:
    driver: bridge