services:
  # BANCO DE DADOS (MySQL) 
  urbancandy-db:
    image: mysql:8.0
    container_name: urbancandy-mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: urbancandy_dockercompose
      MYSQL_ROOT_PASSWORD: ADMIN
    ports:
      - '3306:3306'
    volumes:
      - urbancandy_db_data:/var/lib/mysql
    networks:
      - urbancandy-network
    command: --default-authentication-plugin=mysql_native_password

  #  BACKEND 
  urbancandy-backend:
    container_name: urbancandy-backend-container
    restart: on-failure
    build: ./UrbanCandy_back 
    image: urbancandy-backend:v9
    environment:
      JWT_SECRET: uogvyfivcyifvcgifcvyf
      DB_HOST: urbancandy-db
      DB_USER: root
      DB_PASSWORD: ADMIN
      DB_NAME: urbancandy_dockercompose
    volumes:
      - ./UrbanCandy_back:/app
      - /app/node_modules
      - /app/dist             
      - ./UrbanCandy_back/uploads:/app/uploads
    networks:
      - urbancandy-network
    depends_on:
      - urbancandy-db

  # FRONTEND
  urbancandy-frontend:
    build: ./UrbanCandy_front
    image: urbancandy-frontend:latest
    container_name: urbancandy-frontend-container
    restart: always
    networks:
      - urbancandy-network

  # Nginx
  urbancandy-nginx:
    image: nginx:alpine
    container_name: urbancandy-nginx-container
    restart: always
    ports:
      - '80:80' 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - urbancandy-network
    depends_on:
      - urbancandy-frontend
      - urbancandy-backend

volumes:
  urbancandy_db_data:

networks:
  urbancandy-network:
    driver: bridge